export interface Level {
  id: number;
  name: string;
  width: number;
  height: number;
  goalScore: number;
  maxMoves: number; // New property for maximum moves
  difficulty: 'easy' | 'medium' | 'hard';
  description: string;
  hasIce?: boolean; // New optional property for ice levels
}

export const LEVEL_DATA: Level[] = [
  {
    id: 1,
    name: "Beginner's Grove",
    width: 8,
    height: 8,
    goalScore: 1000,
    maxMoves: 30, // Example: 30 moves for level 1
    difficulty: 'easy',
    description: "A gentle start to your matching adventure. Learn the ropes!",
  },
  {
    id: 2,
    name: "Forest Path",
    width: 9,
    height: 9,
    goalScore: 2500,
    maxMoves: 40, // Example: 40 moves for level 2
    difficulty: 'medium',
    description: "The path gets a little trickier. Keep an eye out for bigger matches!",
  },
  {
    id: 3,
    name: "Mountain Peak",
    width: 10,
    height: 10,
    goalScore: 5000,
    maxMoves: 50, // Example: 50 moves for level 3
    difficulty: 'hard',
    description: "Reach new heights! This level demands strategic thinking.",
  },
  {
    id: 4,
    name: "Volcano Lair",
    width: 11,
    height: 11,
    goalScore: 8000,
    maxMoves: 60, // Example: 60 moves for level 4
    difficulty: 'hard',
    description: "Beware the heat! Only the best can conquer this fiery challenge.",
  },
  {
    id: 5,
    name: "Ocean Depths",
    width: 12,
    height: 12,
    goalScore: 12000,
    maxMoves: 70, // Example: 70 moves for level 5
    difficulty: 'hard',
    description: "Dive deep into the ocean. Matches are hidden in plain sight!",
  },
  {
    id: 6,
    name: "Quick Challenge",
    width: 6,
    height: 6,
    goalScore: 500,
    maxMoves: 5,
    difficulty: 'easy',
    description: "A very quick challenge with limited moves.",
  },
  {
    id: 7,
    name: "Crystal Caves",
    width: 9,
    height: 9,
    goalScore: 6000,
    maxMoves: 55,
    difficulty: 'medium',
    description: "Explore the shimmering depths. Careful planning is key!",
  },
  {
    id: 8,
    name: "Haunted Mansion",
    width: 10,
    height: 10,
    goalScore: 9000,
    maxMoves: 65,
    difficulty: 'hard',
    description: "Spooky and challenging. Can you clear the board?",
  },
  {
    id: 9,
    name: "Sky Garden",
    width: 11,
    height: 11,
    goalScore: 13000,
    maxMoves: 75,
    difficulty: 'hard',
    description: "A serene challenge above the clouds. Aim for the sky!",
  },
  {
    id: 10,
    name: "Ancient Ruins",
    width: 12,
    height: 12,
    goalScore: 17000,
    maxMoves: 85,
    difficulty: 'hard',
    description: "Unearth the secrets of the past. Strategy is your best tool.",
  },
  {
    id: 11,
    name: "Neon City",
    width: 9,
    height: 9,
    goalScore: 7000,
    maxMoves: 60,
    difficulty: 'medium',
    description: "Bright lights, big challenges. Stay focused!",
  },
  {
    id: 12,
    name: "Enchanted Forest",
    width: 10,
    height: 10,
    goalScore: 10000,
    maxMoves: 70,
    difficulty: 'hard',
    description: "Magical and mysterious. Discover the hidden matches.",
  },
  {
    id: 13,
    name: "Lost World",
    width: 11,
    height: 11,
    goalScore: 14000,
    maxMoves: 80,
    difficulty: 'hard',
    description: "Venture into the unknown. Only the brave succeed.",
  },
  {
    id: 14,
    name: "Space Station",
    width: 12,
    height: 12,
    goalScore: 18000,
    maxMoves: 90,
    difficulty: 'hard',
    description: "A cosmic challenge awaits. Reach for the stars!",
  },
  {
    id: 15,
    name: "Pirate Cove",
    width: 9,
    height: 9,
    goalScore: 8000,
    maxMoves: 65,
    difficulty: 'medium',
    description: "Ahoy, matey! Find the hidden treasure matches.",
  },
  {
    id: 16,
    name: "Robot Factory",
    width: 10,
    height: 10,
    goalScore: 11000,
    maxMoves: 75,
    difficulty: 'hard',
    description: "Gears and gadgets galore. Can you assemble the matches?",
  },
  {
    id: 17,
    name: "Sweet Dreams",
    width: 11,
    height: 11,
    goalScore: 15000,
    maxMoves: 85,
    difficulty: 'hard',
    description: "A sugary challenge. Match the sweets to win!",
  },
  {
    id: 18,
    name: "Jurassic Park",
    width: 12,
    height: 12,
    goalScore: 19000,
    maxMoves: 95,
    difficulty: 'hard',
    description: "Dinosaurs roam free. Can you survive the match?",
  },
   {
    id: 19,
    name: "Ninja Dojo",
    width: 10,
    height: 10,
    goalScore: 12000,
    maxMoves: 80,
    difficulty: 'hard',
    description: "Stealth and skill are needed. Become a match master!",
  },
  {
    id: 20,
    name: "Viking Village",
    width: 11,
    height: 11,
    goalScore: 16000,
    maxMoves: 90,
    difficulty: 'hard',
    description: "Raid and match! Conquer the Viking challenge.",
  },
  {
    id: 21,
    name: "Break the Ice",
    width: 8,
    height: 8,
    goalScore: 1000, // Score goal can be lower if ice clearing is the main objective
    maxMoves: 40,
    difficulty: 'medium',
    description: "Match pieces on top of the ice to break it! Clear all ice to win.",
    hasIce: true, // This level has ice!
  },
  {
    id: 22,
    name: "Frozen Peaks",
    width: 9,
    height: 9,
    goalScore: 7500,
    maxMoves: 50,
    difficulty: 'medium',
    description: "The ice is thicker here. Plan your moves carefully!",
    hasIce: true,
  },
  {
    id: 23,
    name: "Desert Oasis",
    width: 10,
    height: 10,
    goalScore: 10000,
    maxMoves: 60,
    difficulty: 'hard',
    description: "A mirage of matches. Find the hidden combos!",
  },
  {
    id: 24,
    name: "Cloud Kingdom",
    width: 11,
    height: 11,
    goalScore: 14000,
    maxMoves: 70,
    difficulty: 'hard',
    description: "Float among the clouds. High scores await!",
  },
  {
    id: 25,
    name: "Deep Sea Trench",
    width: 12,
    height: 12,
    goalScore: 18000,
    maxMoves: 80,
    difficulty: 'hard',
    description: "Pressure is on! Clear the deepest matches.",
  },
  {
    id: 26,
    name: "Magma Core",
    width: 8,
    height: 8,
    goalScore: 6000,
    maxMoves: 45,
    difficulty: 'medium',
    description: "Hot matches in the core. Don't melt under pressure!",
  },
  {
    id: 27,
    name: "Ice Palace",
    width: 10,
    height: 10,
    goalScore: 11000,
    maxMoves: 65,
    difficulty: 'hard',
    description: "A grand challenge of ice. Break through to victory!",
    hasIce: true,
  },
  {
    id: 28,
    name: "Starry Night",
    width: 11,
    height: 11,
    goalScore: 15000,
    maxMoves: 75,
    difficulty: 'hard',
    description: "Match the constellations. A celestial journey!",
  },
  {
    id: 29,
    name: "Jungle Temple",
    width: 9,
    height: 9,
    goalScore: 8500,
    maxMoves: 55,
    difficulty: 'medium',
    description: "Uncover ancient secrets in the dense jungle.",
  },
  {
    id: 30,
    name: "Cyber City",
    width: 12,
    height: 12,
    goalScore: 19000,
    maxMoves: 85,
    difficulty: 'hard',
    description: "A futuristic challenge. Connect the circuits!",
  },
  {
    id: 31,
    name: "Winter Wonderland",
    width: 10,
    height: 10,
    goalScore: 13000,
    maxMoves: 70,
    difficulty: 'hard',
    description: "A festive ice challenge. Clear the snow-covered board!",
    hasIce: true,
  },
];
